# Created in the VideoProcessMining project
TRAIN:
  BATCH_SIZE: 3
  EVAL_PERIOD: 1
  CHECKPOINT_PERIOD: 1
  AUTO_RESUME: True
#  CHECKPOINT_FILE_PATH: #Download the checkpoint from the original SlowFast repository (https://dl.fbaipublicfiles.com/pyslowfast/model_zoo/kinetics400/SLOWFAST_8x8_R50.pkl) and insert the path to the checkpoint here
  CHECKPOINT_TYPE: caffe2
DATA:
  NUM_FRAMES: 32
  SAMPLING_RATE: 2
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 224
  INPUT_CHANNEL_NUM: [3, 3]
DETECTION:
  ENABLE: True
  ALIGNED: True
CUSTOM_DATASET:
  MULTIPLE_ACTION_POSSIBLE: False
  IMG_PROC_BACKEND: "cv2"
  FRAME_RATE: 30
SLOWFAST:
  ALPHA: 4
  BETA_INV: 8
  FUSION_CONV_CHANNEL_RATIO: 2
  FUSION_KERNEL_SZ: 7
RESNET:
  ZERO_INIT_FINAL_BN: True
  WIDTH_PER_GROUP: 64
  NUM_GROUPS: 1
  DEPTH: 50
  TRANS_FUNC: bottleneck_transform
  STRIDE_1X1: False
  NUM_BLOCK_TEMP_KERNEL: [[3, 3], [4, 4], [6, 6], [3, 3]]
  SPATIAL_DILATIONS: [[1, 1], [1, 1], [1, 1], [2, 2]]
  SPATIAL_STRIDES: [[1, 1], [2, 2], [2, 2], [1, 1]]
NONLOCAL:
  LOCATION: [[[], []], [[], []], [[], []], [[], []]]
  GROUP: [[1, 1], [1, 1], [1, 1], [1, 1]]
  INSTANTIATION: dot_product
  POOL: [[[1, 2, 2], [1, 2, 2]], [[1, 2, 2], [1, 2, 2]], [[1, 2, 2], [1, 2, 2]], [[1, 2, 2], [1, 2, 2]]]
SOLVER:
  BASE_LR: 0.0036 # If you use head only a lowe value (e.g., 0.0003) may be more suitable
  LR_POLICY: steps_with_relative_lrs
  STEPS: [14, 16, 18, 19]
  LRS: [1, 0.25, 0.1, 0.025]
  MAX_EPOCH: 20
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-7
  WARMUP_EPOCHS: 15.0
  WARMUP_START_LR: 0.0000125
  OPTIMIZING_METHOD: sgd
MODEL:
  NUM_CLASSES: 10
  ARCH: slowfast
  MODEL_NAME: SlowFast
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.5
  HEAD_ACT: "softmax"
TEST:
  BATCH_SIZE: 1
DATA_LOADER:
  NUM_WORKERS: 2
  PIN_MEMORY: True
NUM_GPUS: 1
RNG_SEED: 0
TENSORBOARD:
  ENABLE: True
PREPROCESS:
  COMPUTE_RGB_MEAN_AND_STD_DATALOADER_BATCH_SIZE: 10
  COMPUTE_RGB_MEAN_AND_STD_DATALOADER_NUM_WORKERS: 2
DEMO:
  VIDEO_DISPLAY_SCALING_FACTOR: 0.85
  DEEPSORT_NN_BUDGET: 1000
DETECTRON:
  DEMO_MIN_BOX_HEIGHT: 360
#ACTIONRECOGNIZER:
#  CHECKPOINT_FILE_PATH: "" # Insert the path to your final activity recognition model obtained during training