# Created in the VideoProcessMining project
DATA:
  NUM_FRAMES: 32
  SAMPLING_RATE: 2
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 224
  INPUT_CHANNEL_NUM: [3, 3]
DETECTION:
  ENABLE: True
  ALIGNED: True
CUSTOM_DATASET:
  DETECTION_SCORE_THRESH: 0.9
  BGR: False
  MULTIPLE_ACTION_POSSIBLE: False
  IMG_PROC_BACKEND: "cv2"
  VALID_FRAMES_START_SECOND: 0
  VALID_FRAMES_END_SECOND: 100000
  FRAME_RATE: 30
SLOWFAST:
  ALPHA: 4
  BETA_INV: 8
  FUSION_CONV_CHANNEL_RATIO: 2
  FUSION_KERNEL_SZ: 7
RESNET:
  ZERO_INIT_FINAL_BN: True
  WIDTH_PER_GROUP: 64
  NUM_GROUPS: 1
  DEPTH: 50
  TRANS_FUNC: bottleneck_transform
  STRIDE_1X1: False
  NUM_BLOCK_TEMP_KERNEL: [[3, 3], [4, 4], [6, 6], [3, 3]]
  SPATIAL_DILATIONS: [[1, 1], [1, 1], [1, 1], [2, 2]]
  SPATIAL_STRIDES: [[1, 1], [2, 2], [2, 2], [1, 1]]
NONLOCAL:
  LOCATION: [[[], []], [[], []], [[], []], [[], []]]
  GROUP: [[1, 1], [1, 1], [1, 1], [1, 1]]
  INSTANTIATION: dot_product
  POOL: [[[1, 2, 2], [1, 2, 2]], [[1, 2, 2], [1, 2, 2]], [[1, 2, 2], [1, 2, 2]], [[1, 2, 2], [1, 2, 2]]]
BN:
  USE_PRECISE_STATS: False
  NUM_BATCHES_PRECISE: 200
MODEL:
  NUM_CLASSES: 10
  ARCH: slowfast
  MODEL_NAME: SlowFast
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.5
  HEAD_ACT: "softmax"
DATA_LOADER:
  NUM_WORKERS: 4
  PIN_MEMORY: True
NUM_GPUS: 4
NUM_SHARDS: 1
RNG_SEED: 0
TRAIN:
  ENABLE: False
TEST:
  ENABLE: False
PREPROCESS:
  ENABLE: False
DEMO:
  ENABLE: True
  VIDEO_SHOW_VIDEO_ENABLE: False
  VIDEO_SHOW_VIDEO_DEBUGGING_INFO: False
  VIDEO_EXPORT_VIDEO_ENABLE: False
  VIDEO_ACTION_CATEGORY_DISPLAY_SCORE_TRESH: 0.0
  VIDEO_DISPLAY_SCALING_FACTOR: 0.85
  VIDEO_ACTION_DISPLAY_DURATION_MILLISECONDS: 1
  EXPORT_EXPORT_RESULTS: True
  EXPORT_MIN_CATEGORY_EXPORT_SCORE: 0.30
  DEEPSORT_REID_CKPT: "./deep_sort/deep/checkpoint/ckpt.t7"
  DEEPSORT_MAX_DIST: 0.05
  DEEPSORT_NMS_MAX_OVERLAP: 0.85
  DEEPSORT_MAX_IOU_DISTANCE: 0.3
  DEEPSORT_MAX_AGE: 300
  DEEPSORT_N_INIT: 30
  DEEPSORT_NN_BUDGET: 1000
DETECTRON:
  DETECTION_MODEL_CFG: "COCO-Detection/faster_rcnn_R_50_FPN_3x.yaml"
  MODEL_WEIGHTS: "detectron2://COCO-Detection/faster_rcnn_R_50_FPN_3x/137849458/model_final_280758.pkl"
  DEMO_PERSON_SCORE_THRESH: 0.5
  DEMO_MIN_BOX_HEIGHT: 360
  DEMO_BATCH_SIZE: 10
ACTIONRECOGNIZER:
  BGR: False
  IMG_PROC_BACKEND: "cv2"
  CHECKPOINT_TYPE: "pytorch"